SEED: 42 # random seed for reproducibility
LSTM:
  FEATURE_LENGTH: 26 # the number of features in the input data
  HIDDEN_SIZE: 1 # the number of features in the hidden state
  SEQUENCE_LENGTH: 5 # the number of time steps in the input sequence
  BATCH_SIZE: 1 # the number of samples in each batch
  NUM_LAYERS: 1 # the number of recurrent layers
  DROPOUT_RATE: 0.0 # the rate in which to drop connections
  LEARNING_RATE: 0.001 # the learning rate
  NUM_EPOCHS: 100 # the number of epochs
  DEVICES: auto # the devices to use for training
  ACCELERATOR: auto # the accelerator to use for training
SIMULATOR:
  SHORT_COUNT: 10 # the number of short positions to take
  LONG_COUNT: 10 # the number of long positions to take
  SIMULATION_DAYS: 100 # the number of days to simulate
  BATCH_SIZE: 1 # the number of samples in each batch
  SEQUENCE_LENGTH: 5 # the number of time steps in the input sequence
